# v2.1 for Orb Compatibility
version: 2.1
jobs:
  info:
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: bash scripts/install-utils.sh

  test-auth:
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: bash scripts/install-utils.sh
      - run: bash scripts/decrypt-key.sh $KEY_PASSWORD $PASS_KEY_PATH $KEY_PATH
      - run: bash scripts/jwt-login.sh $CLIENT_ID $KEY_PATH $USER $ALIAS $INSTANCE_URL

  scratch-validate:
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: bash scripts/install-utils.sh
      - run: bash scripts/decrypt-key.sh $KEY_PASSWORD $PASS_KEY_PATH $KEY_PATH
      - run: bash scripts/jwt-login.sh $CLIENT_ID $KEY_PATH $USER $ALIAS $INSTANCE_URL
      - run: bash scripts/validate.sh "PR$CIRCLE_PR_NUMBER-$CIRCLE_BRANCH"

  deploy-mdtapi:
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: bash scripts/install-utils.sh
      - run: bash scripts/decrypt-key.sh $KEY_PASSWORD $PASS_KEY_PATH $KEY_PATH
      - run: bash scripts/jwt-login.sh $CLIENT_ID $KEY_PATH $USER $ALIAS $INSTANCE_URL
      - run: bash scripts/deploy-mdtapi.sh $ALIAS

  hold:
    docker:
      - image: alpine
    steps:
      - echo "Holding for Approval."

workflows:
  test-auth-int:
    jobs:
      - hold:
          type: approval
      - test-auth:
          context: INT
          requires:
            - hold

  test-auth-uat:
    jobs:
      - hold:
          type: approval
      - test-auth:
          context: UAT
          requires:
            - hold

  test-auth-stg:
    jobs:
      - hold:
          type: approval
      - test-auth:
          context: STG
          requires:
            - hold

  test-auth-hub:
    jobs:
      - hold:
          type: approval
      - test-auth:
          context: HUB
          requires:
            - hold

  feature-pr:
    jobs:
      - scratch-validate:
          context: HUB
          filters:
            branches:
              only: feature/*

  deploy-int:
    jobs:
      - deploy-mdtapi:
          context: INT
          filters:
            branches:
              only: develop

  release-uat:
    jobs:
      - hold:
          type: approval
      - deploy-mdtapi:
          requires:
            - hold
          context: UAT
          filters:
            branches:
              only: release/*

  release-stg:
    jobs:
      - hold:
          type: approval
      - deploy-mdtapi:
          requires:
            - hold
          context: STG
          filters:
            branches:
              only: release/*

  release-prod:
    jobs:
      - hold:
          type: approval
      - deploy-mdtapi:
          requires:
            - hold
          context: HUB
          filters:
            branches:
              only: master
