# v2.1 for Orb Compatibility
version: 2.1
jobs:
  info:
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: bash scripts/install-utils.sh

  test-auth:
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: bash scripts/install-utils.sh
      - run: mkdir keys
      - run: echo $SERVER_KEY > $KEY_PATH
      - run: bash scripts/jwt-login.sh $CLIENT_ID $KEY_PATH $USER $ALIAS $INSTANCE_URL

  hold:
    docker:
      - image: alpine
    steps:
      - echo "Holding for Approval."

workflows:
  test-auth-int:
    jobs:
      - hold:
          type: approval
      - test-auth:
          context: INT
          requires:
            - hold

  # test-auth-uat:
  #   jobs:
  #     - test-auth $UAT_ALIAS $UAT_CLIENT_ID $UAT_USER $UAT_URL $KEY_PATH

  # test-auth-stg:
  #   jobs:
  #     - test-auth $STG_ALIAS $STG_CLIENT_ID $STG_USER $STG_URL $KEY_PATH

  # test-auth-hub:
  #   jobs:
  #     - test-auth $HUB_ALIAS $HUB_CLIENT_ID $HUB_USER $HUB_URL $KEY_PATH
